=== ASCS-eV/EVES/EVES/EVES-003/erc721-schemas/erc721_token_metadata-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/asset",
  "title": "ERC-721 Token Metadata",
  "definitions": {
    "asset": {
      "type": "object",
      "additionalProperties": true,
      "required": [
        "name",
        "image"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Identifies the asset to which this NFT represents."
        },
        "description": {
          "type": "string",
          "description": "Describes the asset to which this NFT represents."
        },
        "image": {
          "type": "string",
          "format": "uri-reference",
          "description": "A URI pointing to a resource with mime type image/* representing the asset. Maps to TZIP-21 displayUri."
        },
        "animation_url": {
          "type": "string",
          "format": "uri-reference",
          "description": "A URI pointing to the actual asset content (e.g. asset.zip download URL). Maps to TZIP-21 artifactUri."
        },
        "external_url": {
          "type": "string",
          "format": "uri-reference",
          "description": "A URI pointing to an external page with additional information about the asset (e.g. domain metadata on IPFS). Maps to TZIP-21 externalUri."
        },
        "background_color": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{6}$",
          "description": "Background color of the item on OpenSea. Must be a six-character hexadecimal without a pre-pended #."
        },
        "minter": {
          "type": "string",
          "description": "The DID of the LegalEntity (OrganizationParticipant) responsible for minting the asset, as defined in EVES-008 (e.g. did:ethr:<chainIdHex>:<address>). EVES extension."
        },
        "creators": {
          "type": "array",
          "description": "The primary person, people, or organization(s) responsible for creating the intellectual content of the asset.",
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "contributors": {
          "type": "array",
          "description": "The person, people, or organization(s) that have made substantial creative contributions to the asset.",
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "publishers": {
          "type": "array",
          "description": "The person, people, or organization(s) primarily responsible for distributing or making the asset available to others in its present form.",
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "date": {
          "type": "string",
          "format": "date-time",
          "description": "A date associated with the creation or availability of the asset."
        },
        "type": {
          "type": "string",
          "description": "A broad definition of the type of content of the asset."
        },
        "rights": {
          "type": "string",
          "description": "A statement about the asset rights, e.g. an SPDX license identifier."
        },
        "rights_uri": {
          "type": "string",
          "format": "uri-reference",
          "description": "Links to a statement of rights (e.g. full license text or smart contract DID). Maps to TZIP-21 rightsUri. EVES extension."
        },
        "identifier": {
          "type": "string",
          "description": "A string or number used to uniquely identify the asset. Ex. URL, URN, UUID, ISBN, DID, etc."
        },
        "formats": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/format"
          }
        },
        "attributes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/attribute"
          },
          "description": "OpenSea-style attributes describing traits of the asset."
        }
      }
    },
    "format": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "uri": {
          "type": "string",
          "format": "uri-reference",
          "description": "A URI to the asset represented in this format."
        },
        "hash": {
          "type": "string",
          "description": "A checksum hash of the content of the asset in this format."
        },
        "mimeType": {
          "type": "string",
          "description": "Media (MIME) type of the format."
        },
        "fileSize": {
          "type": "integer",
          "description": "Size in bytes of the content of the asset in this format."
        },
        "fileName": {
          "type": "string",
          "description": "Filename for the asset in this format. For display purposes."
        },
        "duration": {
          "type": "string",
          "format": "time",
          "description": "Time duration of the content of the asset in this format."
        },
        "dimensions": {
          "$ref": "#/definitions/dimensions",
          "description": "Dimensions of the content of the asset in this format."
        },
        "dataRate": {
          "$ref": "#/definitions/dataRate",
          "description": "Data rate which the content of the asset in this format was captured at."
        }
      }
    },
    "attribute": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "trait_type": {
          "type": "string",
          "description": "Name of the trait."
        },
        "value": {
          "description": "Value of the trait.",
          "oneOf": [
            { "type": "string" },
            { "type": "number" }
          ]
        },
        "display_type": {
          "type": "string",
          "description": "Display type hint for the trait (e.g. number, boost_percentage, boost_number, date)."
        }
      },
      "required": [
        "trait_type",
        "value"
      ]
    },
    "dataRate": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "value": {
          "type": "integer"
        },
        "unit": {
          "type": "string"
        }
      },
      "required": [
        "unit",
        "value"
      ]
    },
    "dimensions": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "value": {
          "type": "string"
        },
        "unit": {
          "type": "string"
        }
      },
      "required": [
        "unit",
        "value"
      ]
    }
  }
}

=== ASCS-eV/EVES/EVES/EVES-003/example/erc721_token_metadata.json
{
  "name": "TestfeldNiedersachsen_ALKS_ODR_sample",
  "description": "simple hdmap example file on Testfeld Niedersachsen for ALKS scenario",
  "image": "ipfs://bafybeief5r2xgciehzhx6c4kbooifsnbjpiifjei36lpi3kzcdmpr2wvue",
  "animation_url": "https://assets.envited-x.net/bafybeifo6ve5i6542vi6ruuflxdqtcmcisdtwlqefq2e5a33tljsaqxhpm",
  "external_url": "ipfs://bafkreicuwg3s4uvei2iu2p5eobozghdodtwhwoi6qiawhwqj3nflrk6dxi",
  "attributes": [
    {
      "trait_type": "Standard",
      "value": "GaiaX"
    },
    {
      "trait_type": "Publisher",
      "value": "ASCS"
    },
    {
      "trait_type": "Ecosystem",
      "value": "ENVITED-X"
    },
    {
      "trait_type": "Specification",
      "value": "EVES"
    },
    {
      "trait_type": "Token Type",
      "value": "nft"
    },
    {
      "trait_type": "Format",
      "value": "ASAM OpenDRIVE 1.6"
    },
    {
      "trait_type": "Ontology",
      "value": "https://w3id.org/ascs-ev/envited-x/hdmap/v6/"
    },
    {
      "trait_type": "Ontology",
      "value": "https://w3id.org/ascs-ev/envited-x/envited-x/v3/"
    }
  ],
  "minter": "did:pkh:eip155:42793:0xAa9De953e5C50dbfF35B43C60bdCb5E1ceCcFD58",
  "creators": [
    "Automotive Solution Center for Simulation e.V."
  ],
  "publishers": [
    "Automotive Solution Center for Simulation e.V.",
    "ENVITED-X Data Space"
  ],
  "date": "2025-02-17T00:00:00+00:00",
  "type": "EVES-003 https://github.com/ASCS-eV/EVES",
  "rights": "MPL-2.0",
  "rights_uri": "https://www.mozilla.org/en-US/MPL/2.0/",
  "identifier": "did:web:registry.gaia-x.eu:HdMap:DjHgK5ErTBow1Ya3J05tW9l12skGWgZn6kA9",
  "formats": [
    {
      "uri": "https://assets.envited-x.net/bafybeifo6ve5i6542vi6ruuflxdqtcmcisdtwlqefq2e5a33tljsaqxhpm",
      "hash": "bafybeifo6ve5i6542vi6ruuflxdqtcmcisdtwlqefq2e5a33tljsaqxhpm",
      "mimeType": "application/zip",
      "fileSize": 7711664,
      "fileName": "Testfeld_Niedersachsen_ALKS_xodr_sample.zip"
    },
    {
      "uri": "ipfs://bafkreicuwg3s4uvei2iu2p5eobozghdodtwhwoi6qiawhwqj3nflrk6dxi",
      "hash": "bafkreicuwg3s4uvei2iu2p5eobozghdodtwhwoi6qiawhwqj3nflrk6dxi",
      "mimeType": "application/ld+json",
      "fileSize": 6574,
      "fileName": "hdmap_instance.json"
    },
    {
      "uri": "ipfs://bafkreigxkhnuuyjrb2nyduivdaqbrbuw7zcjf6aaslvlufvmgv5bfsh6u4",
      "hash": "bafkreigxkhnuuyjrb2nyduivdaqbrbuw7zcjf6aaslvlufvmgv5bfsh6u4",
      "mimeType": "application/ld+json",
      "fileSize": 21630,
      "fileName": "manifest_reference.json"
    },
    {
      "uri": "ipfs://bafkreie2yjoudxlayordup63se7wbj6vroaoyqzcuixqcchpmd23ufno6u",
      "hash": "bafkreie2yjoudxlayordup63se7wbj6vroaoyqzcuixqcchpmd23ufno6u",
      "mimeType": "application/ld+json",
      "fileSize": 5572,
      "fileName": "envited-x_manifest.json"
    },
    {
      "uri": "ipfs://bafybeief5r2xgciehzhx6c4kbooifsnbjpiifjei36lpi3kzcdmpr2wvue",
      "hash": "bafybeief5r2xgciehzhx6c4kbooifsnbjpiifjei36lpi3kzcdmpr2wvue",
      "mimeType": "image/png",
      "dimensions": {
        "value": "1095x850",
        "unit": "px"
      },
      "fileSize": 2397906,
      "fileName": "Testfeld_Niedersachsen_ALKS_..._impression-01.png"
    }
  ]
}
